name: Dump Database

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Run]
    types:
      - completed

permissions:
  contents: write

jobs:
  dump-db:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Dump tables to SQL
        uses: ryohidaka/action-dump-sqlite@v0.1.0
        with:
          db: "db/archives.db"
          output: "./db/dump.sql"

      - name: Commit and push changes
        uses: ryohidaka/action-commit-push@v0.3.0
        with:
          files: "db/dump.sql"
          commit-message: "chore: Update dump file"
          rebase: true
