name: Dump Database

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Run]
    types:
      - completed

jobs:
  dump-db:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Dump tables to SQL
        uses: ryohidaka/action-dump-sqlite@v0.1.0
        with:
          db: "db/archives.db"
          output: "./db/dump.sql"

      - name: Check for changes
        id: check_changes
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"

          git add db/dump.sql
          if git diff --cached --quiet; then
            echo "No changes detected in dump file. Skipping commit and push."
            echo "changes_detected=false" >> $GITHUB_OUTPUT
            exit 0
          else
            echo "changes_detected=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.check_changes.outputs.changes_detected == 'true'
        run: |
          git fetch
          git pull
          git commit -m "chore: Update dump file"
          git push origin main
