name: Generate HTML

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Run]
    types:
      - completed
  push:
    paths:
      - "generate-html/**"

permissions:
  contents: write

jobs:
  generate-html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore DB
        uses: ryohidaka/action-restore-sqlite@v0.1.0
        with:
          db: "db/archives.db"
          dump-file: "db/dump.sql"

      - uses: actions/setup-go@v5
        with:
          go-version: "^1.21.3"
          check-latest: true
          cache-dependency-path: |
            generate-html/go.sum

      - name: Run generate-html
        run: cd generate-html && go run cmd/main.go

      - name: Commit and push changes
        uses: ryohidaka/action-commit-push@v0.3.0
        with:
          files: "docs/index.html"
          commit-message: "chore: Update html file"
          rebase: true
