name: Run

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"
  push:
    paths:
      - "goo-gl-archives/**"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore DB
        uses: ryohidaka/action-restore-sqlite@v0.1.0
        with:
          db: "db/archives.db"
          dump-file: "db/dump.sql"

      - uses: actions/setup-go@v5
        with:
          go-version: "^1.21.3"
          check-latest: true
          cache-dependency-path: |
            goo-gl-archives/go.sum

      - name: Run backup
        run: cd goo-gl-archives && go run cmd/main.go

      - name: Dump tables to SQL
        uses: ryohidaka/action-dump-sqlite@v0.1.0
        with:
          db: "db/archives.db"
          output: "./db/dump.sql"

      - name: Set current datetime as env variable
        env:
          TZ: "Asia/Tokyo"
        run: echo "CURRENT_DATETIME=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Commit and push changes
        uses: ryohidaka/action-commit-push@v0.3.0
        with:
          files: "db/dump.sql"
          commit-message: "chore: Update database on ${{ env.CURRENT_DATETIME }}"
          rebase: true
