name: Run

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "^1.21.3"
          check-latest: true
          cache-dependency-path: |
            goo-gl-archives/go.sum

      - name: Run backup
        run: cd goo-gl-archives && go run cmd/main.go

      - name: Set current datetime as env variable
        env:
          TZ: "Asia/Tokyo"
        run: echo "CURRENT_DATETIME=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Check for changes
        id: check_changes
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"

          git add db/archives.db goo-gl-archives/logs
          if git diff --cached --quiet; then
            echo "No changes detected in db. Skipping commit and push."
            echo "changes_detected=false" >> $GITHUB_OUTPUT
            exit 0
          else
            echo "changes_detected=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.check_changes.outputs.changes_detected == 'true'
        run: |
          git fetch
          git pull
          git commit -m "chore: Update database on ${{ env.CURRENT_DATETIME }}"
          git push origin main
