name: Run

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install a specific version
        uses: eifinger/setup-rye@v3
        with:
          version: "latest"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          enable-cache: true

      - name: Run backup
        run: |
          rye sync
          rye run goo-gl-archives

      - name: Set current datetime as env variable
        env:
          TZ: "Asia/Tokyo"
        run: echo "CURRENT_DATETIME=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Commit and Push
        run: |
          if (git diff --shortstat --ignore-submodules | grep '[0-9]'); then
            git config --local user.email "GitHub Actions"
            git config --local user.name "actions@github.com"
            git add db
            git commit -m "chore: Update database on ${{ env.CURRENT_DATETIME }}"
            git push origin main
          fi
