name: Save to Wayback Machine

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Deploy static content to Pages]
    types:
      - completed

jobs:
  save-to-wayback-machine:
    runs-on: ubuntu-latest
    steps:
      - name: Save my blog
        uses: JamieMagee/wayback@v2.0.0
        with:
          url: https://ryohidaka.github.io/goo-gl-archives/
